import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Sparkles, TrendingUp, AlertTriangle, FileText, ArrowRight } from 'lucide-react';
import type { StateDiff } from '../hooks/useSimulation';

interface WhatChangedBannerProps {
  diffs: StateDiff[];
  className?: string;
}

export const WhatChangedBanner: React.FC<WhatChangedBannerProps> = ({ diffs, className = '' }) => {
  if (!diffs || diffs.length === 0) return null;

  const getChipStyle = (type: string) => {
    if (type === 'priority') {
      return {
        bg:     'rgba(239, 68, 68, 0.12)',
        border: 'rgba(239, 68, 68, 0.35)',
        color:  '#F87171',
        glow:   '0 0 10px rgba(239, 68, 68, 0.2)',
        Icon:   TrendingUp,
      };
    }
    if (type === 'state') {
      return {
        bg:     'rgba(245, 158, 11, 0.12)',
        border: 'rgba(245, 158, 11, 0.35)',
        color:  '#FCD34D',
        glow:   '0 0 10px rgba(245, 158, 11, 0.2)',
        Icon:   AlertTriangle,
      };
    }
    if (type === 'event') {
      return {
        bg:     'rgba(59, 130, 246, 0.12)',
        border: 'rgba(59, 130, 246, 0.35)',
        color:  '#60A5FA',
        glow:   '0 0 10px rgba(59, 130, 246, 0.2)',
        Icon:   Sparkles,
      };
    }
    return {
      bg:     'rgba(255, 255, 255, 0.04)',
      border: 'rgba(255, 255, 255, 0.08)',
      color:  '#CBD5E1',
      Icon:   FileText,
    };
  };

  return (
    <AnimatePresence mode="wait">
      <motion.div
        key={diffs.map((d) => d.id).join('-')}
        initial={{ opacity: 0, y: -12, scale: 0.98 }}
        animate={{ opacity: 1, y: 0, scale: 1 }}
        exit={{ opacity: 0, y: -12, scale: 0.98 }}
        transition={{ duration: 0.3, ease: 'easeOut' }}
        className={`rounded-xl p-3 font-mono ${className}`}
        style={{
          background:  'linear-gradient(to right, rgba(37, 99, 235, 0.12), #121821, #121821)',
          border:      '1px solid rgba(59, 130, 246, 0.3)',
          boxShadow:   '0 0 20px -8px rgba(59, 130, 246, 0.25)',
        }}
      >
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2.5">
          {/* ── Label ── */}
          <div className="flex items-center gap-2">
            <span
              className="flex h-7 w-7 items-center justify-center rounded-lg"
              style={{
                background: 'rgba(59, 130, 246, 0.15)',
                border:     '1px solid rgba(59, 130, 246, 0.4)',
              }}
            >
              <Sparkles className="w-4 h-4 animate-pulse" style={{ color: '#60A5FA' }} />
            </span>
            <div>
              <div
                className="text-[11px] font-bold uppercase tracking-wider flex items-center gap-1.5"
                style={{ color: '#60A5FA' }}
              >
                WHAT CHANGED?
                <span
                  className="text-[10px] px-1.5 py-0.5 rounded font-mono"
                  style={{
                    background: 'rgba(59, 130, 246, 0.15)',
                    border:     '1px solid rgba(59, 130, 246, 0.3)',
                    color:      '#93C5FD',
                  }}
                >
                  SIMULATION STEP
                </span>
              </div>
              <p className="text-[11px] font-body" style={{ color: '#9AA4B2' }}>
                Real-time incident state evolution generated by backend intelligence pipeline.
              </p>
            </div>
          </div>

          {/* ── Diff Chips ── */}
          <div className="flex items-center gap-2 flex-wrap">
            {diffs.map((diff) => {
              const { bg, border, color, glow, Icon } = getChipStyle(diff.type);
              return (
                <motion.div
                  key={diff.id}
                  initial={{ scale: 0.8, opacity: 0 }}
                  animate={{ scale: 1, opacity: 1 }}
                  transition={{ duration: 0.2 }}
                  className="flex items-center gap-1.5 px-2.5 py-1 rounded-lg border text-xs font-semibold"
                  style={{ background: bg, borderColor: border, color, boxShadow: glow }}
                >
                  <Icon className="w-3.5 h-3.5 shrink-0" />
                  {diff.from !== undefined && diff.to !== undefined ? (
                    <span className="flex items-center gap-1">
                      <span>{String(diff.from)}</span>
                      <ArrowRight className="w-3 h-3" style={{ color: 'var(--color-muted)' }} />
                      <strong className="font-bold text-white">{String(diff.to)}</strong>
                    </span>
                  ) : (
                    <span>{diff.label}</span>
                  )}
                </motion.div>
              );
            })}
          </div>
        </div>
      </motion.div>
    </AnimatePresence>
  );
};

export default WhatChangedBanner;
